### ISSUE TITLE
Writing a flake8 plugin for docargs

### ISSUE THREAD

**Issue by srstevenson** [janfreyberg/docargs#4]
Flake8 has support for [writing plugins](http://flake8.pycqa.org/en/latest/plugin-development/index.html), which allow it to be extended with additional checks. It would be useful if we could write a plugin for docargs: the main benefit over using docargs as a standalone CLI is that we'd benefit from existing flake8 integrations for text editors and IDEs, so docargs warnings would show inline in the same way as other warnings.

**Comment by janfreyberg** [comment]
This is a great idea! Would be great.

**Comment by janfreyberg** [comment]
I think the issues I see with the current implementation is that importing a file makes lots of things difficult, since python files can conceivably be written to only be importable when the current directory is a specific directory.

I think generally, this would require a slight re-work of the current implementation, probably using the [`ast`](https://docs.python.org/3.7/library/ast.html) module, since you can get function signatures through `ast.FunctionDef.args` and docstrings with `ast.get_docstring`.

Once we have those, we can just use the current comparison functions.
